export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";
export const CREATE_MNEMONIC = "CREATE_MNEMONIC";
export const CREATE_SHORTCODE = "CREATE_SHORTCODE";
export const RESOLVE_SHORTCODE = "RESOLVE_SHORTCODE";
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGOUT_ACCOUNT = "LOGOUT_ACCOUNT";
