import React, { useContext, useEffect, useState } from "react";
import { ThemeContext } from "../../store/themeContext/themeContext";
import { StoreContext } from "../../store/store";
import useStyles from "./podSidebarStyles";
import ButtonPill from "../buttonPill/buttonPill";

export interface Props {}

function PodSidebar(props: Props) {
  const { state, actions } = useContext(StoreContext);
  const { theme } = useContext(ThemeContext);

  const classes = useStyles({ ...props, ...theme });

  useEffect(() => {
    if (state.podsOpened.includes(state.podName))
      actions.getDirectory({ directory: "root", podName: state.podName });
  }, [state.podName, state.podsOpened]);

  return (
    <div className={classes.BoilerPlate}>
      <div className={classes.rowButtons}>
        <ButtonPill
          clickFunction={() => {}}
          text="Private"
          size="small"
        ></ButtonPill>
        <ButtonPill
          clickFunction={() => {}}
          text="Shared"
          size="small"
        ></ButtonPill>
      </div>
      <div className={classes.switchPods}>
        Switch from shared to private pod to see Home pod
      </div>
      <div className={classes.pods}>
        <ButtonPill
          clickFunction={() => {}}
          size="medium"
          text="Create new pod"
        ></ButtonPill>
        {state.pods.map((pod) => {
          return (
            <ButtonPill
              clickFunction={() => {
                actions.setPodName(pod);
                if (!state.podsOpened.includes(pod))
                  actions.openPod({ password: state.password, podName: pod });
              }}
              size="medium"
              text={pod}
            ></ButtonPill>
          );
        })}
      </div>
      <div className={classes.switchPods}>
        My photos pod is an autogenerated Pod that can be used with Fairphoto.
      </div>
    </div>
  );
}

export default React.memo(PodSidebar);
