import React, { useContext, useEffect, useState } from "react";
import { ThemeContext } from "../../store/themeContext/themeContext";
import { StoreContext } from "../../store/store";
import useStyles from "./podSidebarStyles";
import ButtonPill from "../buttonPill/buttonPill";
import { getPods } from "../../store/services/fairOS";

export interface Props {}

function BoilerPlate(props: Props) {
  const { state, actions } = useContext(StoreContext);
  const { theme } = useContext(ThemeContext);

  const classes = useStyles({ ...props, ...theme });
  // const [pods, setPods] = useState(null);
  const pods = ["One", "Two", "Three"];
  useEffect(() => {
    loadPods();
  });
  const loadPods = async () => {
    // setPods();
    // const res = await getPods();
  };
  return (
    <div className={classes.BoilerPlate}>
      <div className={classes.rowButtons}>
        <ButtonPill
          clickFunction={() => {}}
          text="Private"
          size="small"
        ></ButtonPill>
        <ButtonPill
          clickFunction={() => {}}
          text="Shared"
          size="small"
        ></ButtonPill>
      </div>
      <div className={classes.switchPods}>
        Switch from shared to private pod to see Home pod
      </div>
      <div className={classes.pods}>
        <ButtonPill clickFunction={() => {}} text="Create new pod"></ButtonPill>
        {pods.map((pod) => {
          return <ButtonPill clickFunction={() => {}} text={pod}></ButtonPill>;
        })}
      </div>
      <div className={classes.switchPods}>
        My photos pod is an autogenerated Pod that can be used with Fairphoto.
      </div>
    </div>
  );
}

export default React.memo(BoilerPlate);
