export default {
  SEND_FILE:{
    SEND_FILE_REQUEST:"SEND_FILE_REQUEST",
    FILE_SENT_SUCCESS:"FILE_SENT_SUCCESS",
    SENDING_FILE_FAILED:"SENDING_FILE_FAILED",
  },
  GET_DIRECTORY:{
    GET_DIRECTORY_REQUEST:"GET_DIRECTORY_REQUEST",
    GET_DIRECTORY_SUCCESS:"GET_DIRECTORY_SUCCESS",
    GET_DIRECTORY_FAILED:"GET_DIRECTORY_FAILED",
  },
  LOGIN_USER:{
    USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
    USER_LOGIN_PENDING:"USER_LOGIN_PENDING",
    USER_LOGGED_SUCCESS:"USER_LOGGED_SUCCESS",
    USER_LOGGED_FAILED:"USER_LOGGED_FAILED"
  },
  LOG_OUT_USER:{
    USER_LOG_OUT_REQUEST:"USER_LOG_OUT_REQUEST",
    USER_LOGGED_OUT_SUCCESS:"USER_LOGGED_OUT_SUCCESS"
  },
  SET_SYSTEM : "SET_SYSTEM",
  SET_DIRECTORY : "SET_DIRECTORY",
  UNLOCK_SYSTEM :"UNLOCK_SYSTEM",
  STORE_USER_REGISTRATION_INFO: "STORE_USER_REGISTRATION_INFO",
  SEED_PHRASE: {
    SEED_PHRASE_REQUEST:"SEED_PHRASE_REQUEST",
    SEED_PHRASE_PENDING:"SEED_PHRASE_PENDING",
    SEED_PHRASE_SUCCESS:"SEED_PHRASE_SUCCESS",
    SEED_PHRASE_FAILED:"SEED_PHRASE_FAILED"
  },
  CREATE_USER:{
    CREATE_USER_REQUEST:"CREATE_USER_REQUEST",
    CREATE_USER_PENDING:"CREATE_USER_PENDING",
    CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
    CREATE_USER_FAILED:"CREATE_USER_FAILED"
  },
  SET_SEARCH_QUERY : "SET_SEARCH_QUERY"
};
