import React, { useContext, useState } from "react";
import { ThemeContext } from "../../../store/themeContext/themeContext";
import { StoreContext } from "../../../store/store";
import CopyToClipboard from "react-copy-to-clipboard";
import useStyles from "./generateLinkStyles";
import Modal from "../modal/modal";
import { Copy } from "../../icons/icons";

export interface Props {}

function GenerateLink(props: Props) {
  const { state, actions } = useContext(StoreContext);
  const { theme } = useContext(ThemeContext);
  const [, setCopied] = useState(false);
  const classes = useStyles({ ...props, ...theme });

  const copyHandler = () => {
    setCopied(true);
    setTimeout(() => {
      setCopied(false);
    }, 1000);
  };

  return (
    <Modal
      icon={true}
      heading="Generate Referral Link"
      notifyMessage="Invite a friend to use FairDrive by using this link"
    >
      <p className={classes.label}>Refer a friend</p>
      <CopyToClipboard onCopy={copyHandler} text={""}>
        <div className={classes.body}>
          <p>[Pod Share Ref autogenerated]</p>
          <Copy />
        </div>
      </CopyToClipboard>
    </Modal>
  );
}

export default React.memo(GenerateLink);
