import React, { useContext } from "react";
import { ThemeContext } from "../../../store/themeContext/themeContext";
import { StoreContext } from "../../../store/store";
import useStyles from "./generateLinkStyles";
import Modal from "../modal/modal";
import { Copy } from "../../icons/icons";

export interface Props {}

function BoilerPlate(props: Props) {
  const { state, actions } = useContext(StoreContext);
  const { theme } = useContext(ThemeContext);

  const classes = useStyles({ ...props, ...theme });

  return (
    <Modal icon={true} heading='Generate Referral Link' notifyMessage='Invite a friend to use FairDrive by using this link'>
       <p className={classes.label}>Refer a friend</p>
       <div className={classes.body}>
        <p>[Pod Share Ref autogenerated]</p>
        <Copy />
       </div>
    </Modal>
  );
}

export default React.memo(BoilerPlate);
